pipeline {
    agent {
        label "linux"
    }
    environment {
        JDK_TOOL = 'JDK_21'
        MAVEN_TOOL = 'MAVEN'
    }
    stages {
        stage('Deploy') {
            steps {
                dir('birt-runtime') {
                    withMaven(
                            maven: "${MAVEN_TOOL}",
                            jdk: "${JDK_TOOL}"
                    ) {
                        sh """mvn deploy"""
                    }
                }
            }
        }
    }
}