pipeline {
    agent {
        label "linux"
    }
    environment {
        JDK_TOOL = 'JDK_21'
        MAVEN_TOOL = 'MAVEN'
    }
    parameters {
        choice(name: 'deploymentTarget', choices: ['Internal', 'Maven Central'], description: 'Deployment Target')
    }
    stages {
        stage('Config GPG') {
            steps {
                withCredentials([file(credentialsId: 'MAVEN_CENTRAL_SIGNING_KEY', variable: 'SIGNING_KEY')]) {
                    sh """gpg --allow-secret-key-import --import ${SIGNING_KEY}"""
                }
            }
        }
        stage('Deploy internally') {
            when {
                expression { params.deploymentTarget == 'Internal' }
            }
            steps {
                dir('birt-runtime') {
                    withMaven(
                            maven: "${MAVEN_TOOL}",
                            jdk: "${JDK_TOOL}"
                    ) {
                        sh """mvn deploy -Pinternal"""
                    }
                }
            }
        }
        stage('Deploy to Maven Central') {
            when {
                expression { params.deploymentTarget == 'Maven Central' }
            }
            steps {
                dir('birt-runtime') {
                    withMaven(
                            maven: "${MAVEN_TOOL}",
                            jdk: "${JDK_TOOL}"
                    ) {
                        sh """mvn deploy -Pmaven-central"""
                    }
                }
            }
        }
    }
}